In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
path = "E:/CS_Master_Degree_UIUC/CS410_Text_Information_system/Project/Project Submission/CourseProject/Dataset/"
Weights = pd.read_csv(path + "Context_units_weights.csv")
Weights

,pattern,Ralf Steinmetz,Cheng-Wen Wu,Thomas S. Huang,Maja J. Mataric,K. Suzanne Barber,Josef Kittler,Gerald Sommer,Edwin R. Hancock,Masaru Kitsuregawa,...,warp,movement,trade,reusabl,phylogeni,robocup,contextu,intension,nest,distribut resourc
0,Ralf Steinmetz,0.005007,0.003278,0.004386,0.003792,0.003458,0.003737,0.004386,0.004574,0.004262,...,0.003227,0.003914,0.003119,0.004322,0.003792,0.003134,0.003914,0.004453,0.003179,0.002649
1,Cheng-Wen Wu,0.003278,0.005162,0.003851,0.003851,0.004071,0.002692,0.004453,0.004651,0.004330,...,0.003851,0.002292,0.003688,0.003796,0.003851,0.003743,0.003382,0.003910,0.004390,0.003230
2,Thomas S. Huang,0.004386,0.003851,0.005007,0.003227,0.003458,0.003737,0.004386,0.004574,0.004262,...,0.003792,0.003331,0.003119,0.003737,0.003792,0.003684,0.003914,0.003851,0.003737,0.002649
3,Maja J. Mataric,0.003792,0.003851,0.003227,0.004386,0.003458,0.002649,0.004386,0.004003,0.003684,...,0.002690,0.002779,0.003119,0.004322,0.003792,0.003134,0.003331,0.004453,0.003179,0.002649
4,K. Suzanne Barber,0.003458,0.004071,0.003458,0.003458,0.004684,0.003402,0.004003,0.004684,0.004434,...,0.003458,0.002531,0.003241,0.003402,0.004574,0.003880,0.003579,0.004071,0.003940,0.003402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,robocup,0.003134,0.003743,0.003684,0.003134,0.003880,0.003086,0.003684,0.003880,0.003576,...,0.003134,0.002190,0.002550,0.003086,0.004262,0.004138,0.003238,0.003743,0.003629,0.003086
176,contextu,0.003914,0.003382,0.003914,0.003331,0.003579,0.003858,0.004526,0.004734,0.003806,...,0.003914,0.004035,0.003759,0.003858,0.003914,0.003238,0.005328,0.003973,0.003283,0.002738
177,intension,0.004453,0.003910,0.003851,0.004453,0.004071,0.003230,0.004453,0.004651,0.004330,...,0.003278,0.003382,0.003178,0.004390,0.004453,0.003743,0.003973,0.005162,0.003796,0.003230
178,nest,0.003179,0.004390,0.003737,0.003179,0.003940,0.002609,0.003737,0.004502,0.004198,...,0.004322,0.002222,0.003064,0.003131,0.003737,0.003629,0.003283,0.003796,0.004862,0.003131
179,distribut resourc,0.002649,0.003230,0.002649,0.002649,0.003402,0.002115,0.002649,0.003402,0.003086,...,0.003179,0.002222,0.002594,0.002609,0.003179,0.003086,0.002738,0.003230,0.003131,0.003681

In [3]:
def annotation(pattern, weights, K):
    '''
    Given an pattern from the context units, the context units weight matrix and K,
    Output the list of top patterns that have the highest K weights (MI scores) with this author
    '''
    annotation = dict()
    annotation[pattern] = weights.sort_values(by = pattern, ascending = False).iloc[0:K]["pattern"]
    return annotation

In [4]:
# Example1, given a frequent author, output the the top 5 context units as its annotation
author_list = Weights.columns[1:]
author = author_list[0]
rank = 5
author1_annotation = pd.DataFrame(annotation(author, Weights, rank))
author1_annotation

          Ralf Steinmetz
0         Ralf Steinmetz
135           virtuellen
12   Sanjay Kumar Madria
39             workbench
7       Edwin R. Hancock

In [5]:
# Example2, given a frequent title, output the the top 5 context units as its annotation
title_list = Weights.columns[16:]
title = title_list[10]
rank = 5
title1_annotation = pd.DataFrame(annotation(title, Weights, rank))
title1_annotation

         virtual realiti
12   Sanjay Kumar Madria
7       Edwin R. Hancock
9       Roberto Gorrieri
107       analysi access
2        Thomas S. Huang

In [ ]:
output_path = path
author1_annotation.to_csv(output_path + "author_annotation_example1.csv", index = False)
title1_annotation.to_csv(output_path + "title_annotation_example1.csv", index = False)